/* Generated By:JavaCC: Do not edit this line. EjemploAAConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EjemploAAConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ARTICULO = 5;
  /** RegularExpression Id. */
  int SUJETO = 6;
  /** RegularExpression Id. */
  int VERBO = 7;
  /** RegularExpression Id. */
  int NUMERO = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<ARTICULO>",
    "<SUJETO>",
    "<VERBO>",
    "<NUMERO>",
    "\"vodkas,\"",
  };

}
